name: Fetch Versions
permissions:
  contents: write

on:
  push:
    branches:
    - master
    
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Run script
        run: |
          node index.js
      
      - name: Check for versions.json
        run: |
          if [ -f "versions.json" ]; then
            echo "versions.json exists"
          else
            echo "versions.json does not exist"
            exit 1
          fi

      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git add versions.json
          git commit -m "Update versions.json"
          git push
          
